Feature/compare testrail and local tests structure
quantori/Behavioral.Automation pull request #58
Opened 2021-08-12 12:52 UTC by vladimir-s-quantory

Added algorithm for getting or creating sectionId for .feature files in selected folder

2021-08-12 13:41 UTC, SergeyRuzin approved these changes

2021-08-13 07:42 UTC, Brrovko requested changes

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/TestRailSynchronizer/TestRailSynchronizer.cs
> +                    ulong suiteId = 77;
Let's make it configurable, but taking a first suite by default?

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/SectionSynchronizer.cs
> +﻿using System;
Clean up, please

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/SectionSynchronizer.cs
> +namespace GherkinSyncTool.Synchronizers.SectionsSynchronizer
Let's move to `GherkinSyncTool/Synchronizers/TestRailSynchronizer` namespace?

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/SectionSynchronizer.cs
> +        public IEnumerable<TestRailSection> GetSectionsTree(ulong projectId, ulong? suiteId)
Looks like this is internal stuff and can be made private.

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/SectionSynchronizer.cs
> +        public ulong GetOrCreateSectionId(string path, ulong suiteId, ulong projectId)
I think it could be just `GetSectionId`

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/SectionSynchronizer.cs
> +        public ulong GetOrCreateSectionId(string path, ulong suiteId, ulong projectId)
`projectId ` argument can be removed. id can be taking from configs.

2021-08-13 07:42 UTC, Brrovko commented on GherkinSyncTool/GherkinSyncTool/Synchronizers/SectionSynchronizer.cs
> +                    "Section id cannot be null. You cannot put feature files in root folder");
Is it possible that `_testRailClientWrapper.CreateSection()` method returns null?

2021-08-13 10:04 UTC, SergeyRuzin approved these changes

2021-08-13 12:47 UTC, SergeyRuzin approved these changes

2021-08-13 12:48 UTC, merged