Automatic launch of the demo application
quantori/Behavioral.Automation pull request #96
Opened 2022-01-21 12:42 UTC by alspozdnyakov

2022-01-21 12:59 UTC, SergeyRuzin commented on Behavioral.Automation.DemoBindings/Bootstrapper.cs
> +        private const string BaseUrl = "http://localhost:4200";
Can't we use the BaseUrl from ConfigService?

2022-01-21 13:01 UTC, SergeyRuzin commented on src/Behavioral.Automation/nuget.config
> +            <add key="Username" value="alspozdnyakov" />
@andrey-brovko Can we use such creds in open source lib?

2022-01-21 14:12 UTC, vladimir-s-quantory requested changes

2022-01-21 14:12 UTC, vladimir-s-quantory commented on Behavioral.Automation.DemoBindings/Bootstrapper.cs
> +            try
`try ... catch` block is designed to catch exceptions, i.e. abnormal program behavior. Let's try and rewrite this

2022-01-21 14:12 UTC, vladimir-s-quantory commented on src/BlazorApp/Data/WeatherForecast.cs
> +    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
I guess `Math.Round` is a better solution here :)

2022-01-21 14:12 UTC, vladimir-s-quantory commented on src/BlazorApp/Pages/Error.cshtml.cs
> +    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
```suggestion
    public bool RequestIdCanBeShown => !string.IsNullOrEmpty(RequestId);
```

2022-01-21 14:12 UTC, vladimir-s-quantory commented on src/BlazorApp/Shared/MainLayout.razor
> +            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
Do we need a link to MS docs?)

2022-01-21 14:12 UTC, vladimir-s-quantory commented on src/BlazorApp/Shared/NavMenu.razor
> +        <a class="navbar-brand" href="">BlazorApp</a>
What is this link?

2022-01-25 07:21 UTC, andrey-brovko commented
- Let's Rename _Tests folder to Tests?
- Let's move BlazorApp to the Test folder?

2022-01-25 09:39 UTC, vladimir-s-quantory commented on src/BlazorApp/Shared/NavMenu.razor
> +        <h1 class="navbar-brand">DemoApp</h1>
Maybe smthn like `BDD Demo App`?

2022-01-25 09:39 UTC, vladimir-s-quantory approved these changes

2022-01-25 09:45 UTC, SergeyRuzin submitted a review, later dismissed

2022-01-25 10:33 UTC, ILastovka approved these changes

2022-01-25 11:43 UTC, andrey-brovko commented on src/Behavioral.Automation/Behavioral.Automation.csproj
> +        <RepositoryUrl>https://github.com/alspozdnyakov/Behavioral.Automation.git</RepositoryUrl>
The link is incorrect.

2022-01-25 11:44 UTC, andrey-brovko commented on src/Behavioral.Automation/Behavioral.Automation.csproj
> +    <ItemGroup>
Remove please the obj folder.

2022-01-25 11:51 UTC, andrey-brovko commented on Behavioral.Automation.DemoScenarios/Behavioral.Automation.DemoScenarios.csproj
> +    <ProjectReference Include="..\src\BlazorApp\BlazorApp.csproj" />
Why do we need the ref?

2022-01-26 06:25 UTC, andrey-brovko commented on Behavioral.Automation.DemoBindings/Bootstrapper.cs
> +                    FileName = "cmd.exe",
Looks like this will work only for windows?

2022-01-27 09:02 UTC, andrey-brovko approved these changes

2022-01-27 09:22 UTC, SergeyRuzin approved these changes

2022-01-27 12:20 UTC, merged